name: Download PDF, Commit, and Upload to Artifacts

on:
  schedule:
    - cron: '00 09 * * *'  # 2:30 PM SLT
  workflow_dispatch:

jobs:
  download-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client requests beautifulsoup4

    - name: Create metdata folder
      run: mkdir -p metdata  # Ensure the folder is created before running the script

    - name: Run the script to download PDF
      run: python main.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add metdata/*
        git commit -m "Add daily climate update PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

    - name: Upload PDF to artifacts with date
      uses: actions/upload-artifact@v3
      with:
        name: daily-climate-update-${{ steps.date.outputs.current_date }}
        path: metdata/*.pdf  # Upload all PDF files in the metdata folder
