name: Download PDF and Upload to Metdata Folder

on:
  schedule:
    - cron: '00 09 * * *'  # 2:30 PM SLT
  workflow_dispatch:

jobs:
  download-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Create metdata folder
      run: mkdir -p metdata  # Ensure the folder is created before running the script

    - name: Run script to download the PDF
      run: python main.py

    - name: Get current date
      id: date
      run: echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

    - name: Set Up Git
      run: |
        git config --global user.name "metdata04"
        git config --global user.email "metdata04@gmail.com"

    - name: Pull Latest Changes
      run: |
        git pull origin master

    - name: Add Metdata Files
      run: |
        git add metdata/*  # Add all files in the metdata folder
        git commit -m "Add daily climate update PDF - ${{ steps.date.outputs.current_date }}"

    - name: Push Changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
       git push origin master
