name: Extract metstation avg Tmin Data from PDF

on:
  schedule:
    - cron: '20 10 * * *'  # 3.50 PM SLT
  workflow_dispatch:  

jobs:
  extract-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber pandas

    - name: Run extraction script
      run: python metstation_8days_Tmin.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "metdata04"
        git config --global user.email "metdata04@gmail.com"
        git add extracted_data/*
        git commit -m "Extracted metstation 8days Tmin data from climate update PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
