name: Generate Tmax Graph

on:
  schedule:
    # This runs the job every Thursday at 12:00 PM UTC (which is 5.30 PM SLT)
    - cron: '0 12 * * 4'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib

    # Run the script to generate the rainfall graph
    - name: Run extraction script
      run: python daily_Tmax_avg_graph.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "metdata04"
        git config --global user.email "metdata04@gmail.com"
        git add Graphs/Avg_Tmax/*
        git commit -m "Generate Tmax Graph"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
